#!/bin/sh

file="pdns-pipe-nmc"
sfx="linux-glibc6.`uname -m`.`date +%Y-%m-%d`.git-`git describe`"
echo "Making $file.$sfx"

# tried this:
#ghc --make -static -optc-static -optl-shared-libgcc -optl-static \
#           -optl-pthread -pgml g++ "$file"
# but cannot make it "only glibc is shared". And with static glibc,
# getaddrinfo does not work on systems with different glibc.
cabal build
case $? in
0) ;;
*) echo build falied; exit 1 ;;
esac
mv "$file" "$file.$sfx" || exit 1
gpg --detach-sign "$file.$sfx"
